### ISSUE TITLE
[General Query]: Related to this repo

### ISSUE THREAD

**Issue by gitgoap** [ariG23498/ft-pali-gemma#11]
### Questions:

1. **What is your long-term vision for this repository?**

2.  **For issue #6,  `README` file needs to be created for the `object_detection` folder. I am not sure what information exactly should be included in it.**
3.  **I am inspired by your work and your college at HF. Although I am not an expert in fine-tuning, I am a fast learner. Could you suggest any beginner-friendly contributions I can work on?**

@ariG23498

**Comment by ariG23498** [comment]
Hey @gitgoap 

1. I wanted this to be a good beginner friendly set to scripts to start fine tuning PaliGemma. I do not hold any long term vision with this repository.
2. You would need to move files into the folders to refactor the repo.
3. That is great. All I need is passionate people.

**Comment by gitgoap** [comment]
Hey @ariG23498 
Where is the `Image Captioning` training script on Tuxemon?

**Comment by ariG23498** [comment]
https://github.com/ariG23498/fine-tune-paligemma/blob/main/vanilla_ft.py

**Comment by ariG23498** [comment]
Can we safely close this issue?
