### ISSUE TITLE
Save model checkpoint after fine tune

### ISSUE THREAD

**Issue by DigitalPathology** [ariG23498/ft-pali-gemma#2]
After fine tuning process, I want to save the model in that [code](https://github.com/ariG23498/ft-pali-gemma/blob/main/notebooks/license_plate_detection_paligemma_ft.ipynb). What is the correct way?

**Comment by ariG23498** [comment]
Hey @DigitalPathology 

The model is subclassed from the `transformers.PreTrainedModel` so you would be able to use the `push_to_hub` utility to save the model and upload the model to Hugging Face Hub.

Here is the [resource](https://huggingface.co/docs/transformers/en/model_sharing) on how to do.

**Comment by ariG23498** [comment]
Hi @DigitalPathology closing the issue due to inactivity. Please let me know if there are other issues.
