### ISSUE TITLE
Upload Fine-Tuned model for Count Intersection task and update docs

### ISSUE THREAD

**Issue by oliveirabruno01** [ariG23498/ft-pali-gemma#5]
I propose enhancing the `count_intersection` task by enabling it to save and upload the fine-tuned model. Additionally, the model should remain loaded in memory to facilitate running inference directly when using the Jupyter notebook. This proposal is based on the [author's call for contributions](https://x.com/ariG23498/status/1865989123284341013) to improve this repository.

To complement this change, the following documentation updates are suggested:
1. Add a new section to the parent repository's `README`, showcasing the `count_intersection` task with examples of results before and after fine-tuning.
2. Improve the task-specific `README` for better clarity and usability.

I plan to work on these enhancements and submit a pull request. Please let me know if there are additional considerations or suggestions regarding the proposed changes.

**Comment by ariG23498** [comment]
@oliveirabruno01 thanks for the suggestion.

Let's do fine tuning and uploading the model to Hub as the first task. Please feel free to create a PR and tag me in it.
