### ISSUE TITLE
Categorise fine tuning projects

### ISSUE THREAD

**Issue by ariG23498** [ariG23498/ft-pali-gemma#6]
At the current moment we have three projects:
1. Object Detection (PaliGemma 1)
2. Caption fine tune (PaliGemma 1)
3. Count Intersection (PaliGemma 2)

I would like to keep each experiment in a folder like structure as done with [count intersection](https://github.com/ariG23498/fine-tune-paligemma/tree/main/count_intersection).

A folder would have the following:
1. A README which outline what the task is, provides more information of how the experiment was done.
2. A dataset creation script (if required)
3. A training script
4. A training notebook (if possible)

I don't think the folder `paligemma_ft` is required (it has little to no value in the current stage.

ToDos:
- [x] #13 
- [x] #10

**Comment by adityagandhamal** [comment]
Hi @ariG23498! 
Can I take the object detection task?

**Comment by ariG23498** [comment]
@adityagandhamal thank you for taking this up. Please create a PR and tag this issue and me in the PR.

**Comment by gitgoap** [comment]
Let me take the captioning task.

**Comment by ariG23498** [comment]
Please feel free to create a PR, tag this issue and me in the PR.

You can also refer to @adityagandhamal's #10 PR as this was recently merged.

**Comment by ariG23498** [comment]
Closing this issue in favour of completing the TODOs.
